### ISSUE TITLE
Server can't update YML file values for clients to get updated

### ISSUE THREAD

**Issue by gdragon-git** [FelixReuthlinger/CraftingSizeAndSpeed#1]
Hi Felix!
Really appreciate your pragmatic and relatively straightforward mods. 
My issue is that the YML files your mod creates are not server synced themselves. So the YML values don't seem to be serversync'd on change. These makes it hard for server admins to put this mod on their server because any changes to the YML would somehow have to be recirculated to connected clients, and that's not really easy to do. 

I suggest synching the yml file values on change to clients or moving the yml contents to the mod's config file (which seems serversync'd from the source code). According to a friend who mods with serversync, it's possible. Hope you can implement a change like this so that values can be hot-synched live and the mods can work easier for dedicated-server scenarios.

**Comment by FelixReuthlinger** [comment]
thx for the issue post, but not sure what to do in this case. ServerSync is added and there is a reaction on change of value implemented as the server sync does provide the ability to do so. I don't run server and cannot test this out...

**Comment by FelixReuthlinger** [comment]
try https://valheim.thunderstore.io/package/FixItFelix/CraftingSizeAndSpeed/1.0.1/

**Comment by gdragon-git** [comment]
new change allows clients to get updated values on connection

Thank you!
