### ISSUE TITLE
[v1.0.4] No adjustment values in config

### ISSUE THREAD

**Issue by Morpheus1101** [FelixReuthlinger/CraftingSizeAndSpeed#3]
We had prev been using smoothbrains vers but ran into trouble with it creating the same issue thats now occuring with this version..below is exactly what the entire config file looks like when having onyl this mod installed.

```
## Settings file was created by plugin CraftingSizeAndSpeed v1.0.4

## Plugin GUID: FixItFelix.CraftingSizeAndSpeed

[1 - General]

## If 'true' and playing on a server, config can only be changed on server-side configuration, clients cannot override
# Setting type: Boolean
# Default value: true
Lock Configuration = true
```

**Comment by FelixReuthlinger** [comment]
and what is the problem with that?
all configs are generated in other files:
config\FixItFelix.CraftingSizeAndSpeed.Beehive.yaml
config\FixItFelix.CraftingSizeAndSpeed.cfg
config\FixItFelix.CraftingSizeAndSpeed.CookingStation.yaml
config\FixItFelix.CraftingSizeAndSpeed.Fermenter.yaml
config\FixItFelix.CraftingSizeAndSpeed.Smelter.yaml

**Comment by Morpheus1101** [comment]
Are those other cfg Autogenerated or need to be created?  As i dont see any other cfg generated other than FixItFelix.CraftingSizeAndSpeed.cfg

**Comment by Morpheus1101** [comment]
Apologies, i had'nt read mod page to know those configs arent autogenerated, i was used to smoothbrains style being all in the 1 config, this may actually end up being quite substantially better.
